### ISSUE TITLE
s/rust/redox/

### ISSUE THREAD

**Issue by ticki** [Roxxik/redox-doc#8]
In the description

**Comment by Roxxik** [comment]
Do you mean the website?

**Comment by ticki** [comment]
>  Giving an overview over **rust**, will be hosted on the website, later 

from the Repo description

**Comment by Roxxik** [comment]
oh i misread that, it sounded like part of an url :/ but now i see

**Comment by ticki** [comment]
Oh, it's the Vim command for substitute. Just dumb internet slangs.

**Comment by Roxxik** [comment]
_not a vim user_

**Comment by ticki** [comment]
Emacs? AAAAAAAAAAAAAaaaaaaaaaaAAAAAAAAAAAAAAAAAAaaaaaaaaaAAAAAAAAAAAAAAAAAAAaaaaaaaaaAAAAAAAAAAAAAAaaaaaaaaaaa.

**Comment by ticki** [comment]
Flame war intensifies...

**Comment by Roxxik** [comment]
uhm... no neither emacs... I'm a new age graphical texteditor hipster #yolo

**Comment by ticki** [comment]
> editor

**Comment by ticki** [comment]
Only one true editor, ya know.
